### ISSUE TITLE
Annatar broken since RD API changes

### ISSUE THREAD

**Issue by funkypenguin** [g0ldyy/annatar#11]
I think Annatar is currently broken due to the RD API changes. The public instance is logging lots of this:

```
AttributeError: 'list' object has no attribute 'items'
Task exception was never retrieved
future: <Task finished name='Task-4814485' coro=<get_stream_link() done, defined at /usr/local/lib/python3.11/site-packages/annatar/debrid/rd.py:216> exception=AttributeError("'list' object has no attribute 'items'")>
AttributeError: 'list' object has no attribute 'items'
Task exception was never retrieved
future: <Task finished name='Task-6368402' coro=<get_stream_link() done, defined at /usr/local/lib/python3.11/site-packages/annatar/debrid/rd.py:216> exception=AttributeError("'list' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/annatar/debrid/rd.py", line 223, in get_stream_link
    async for cached_files in api.get_instant_availability(
  File "/usr/local/lib/python3.11/site-packages/annatar/debrid/real_debrid_api.py", line 99, in get_instant_availability
    for hash, obj in res.items():
```

**Comment by Destinyg133** [comment]
Seems to be working now

**Comment by Destinyg133** [comment]
Dont know why its closed as completed since it works 50% of the time
